### ISSUE TITLE
Closing the scanner without scanning barcode results in error

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/inventory-count#101]
## Current behavior

When closing the scanner without scanning barcode and clicking backdrop to dismiss the barcode results in search for `backdrop` keyword as sku.

## Expected behavior

Whenever closing the scanner without searching for a code should not show any error.

## Steps to reproduce the issue

- Go to search page
- Click scan, scanner opens up
- Click backdrop to close the scanner without scanning any code
- See that backdrop keyword appears in search bar and Product not found message appears

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

![image](https://user-images.githubusercontent.com/41404838/188850899-ef42305b-e9bf-46f9-8eeb-c016ce447027.png)

**Comment by monieshravichandrran** [comment]
Hey hi!

I would like to try and fix this issue. Can you assign this to me with hacktoberfest tag?

**Comment by ymaheshwari1** [comment]
Hi @monieshravichandrran 
Sure go ahead

**Comment by k2maan** [comment]
Ionic modal returns data and role where the 'role' string defines the element that is dismissing the modal (backdrop in our case).  When the modal is dismissed, the role string is set as undefined else it is assigned that element only (backdrop in our case). So, the modal isn't getting dismissed correctly and that is why result.role returns backdrop

**Comment by k2maan** [comment]
After discussion, we concluded that the function to close the modal on backdrop click can be removed, hence, reverted the 'backdrop' condition code and implemented modal closing using the close icon only (by adding the backdropDismiss check).
