### ISSUE TITLE
Changing the font size of this project

### ISSUE THREAD

**Issue by adpal2003** [hotwax/inventory-count#107]
kindly assign this issue to me ..

![Screenshot 2022-10-14 135709](https://user-images.githubusercontent.com/103566736/195803807-d622e587-a52e-4cfc-8bb0-924ccd110b73.png)

**Comment by amit9177yadav** [comment]
can i work on this issue

**Comment by ymaheshwari1** [comment]
I think there is no need to change the size of the fonts.
