### ISSUE TITLE
Error in console when Logout

### ISSUE THREAD

**Issue by Utkarshkaraiya** [hotwax/inventory-count#108]
## Current behavior

!()
![Screenshot (15)](https://user-images.githubusercontent.com/68690492/195806005-ea2fa736-2701-41f3-a2c3-916cf7069247.png)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by ymaheshwari1** [comment]
Closing as already handled.
