### ISSUE TITLE
Location field not pre-filled correctly 

### ISSUE THREAD

**Issue by Pragyad07** [hotwax/inventory-count#125]
## Current behavior
When the product's stock count is updated, the location field comes prefilled but further, it gives an error while uploading. 
After selecting the location again and saving it, products get uploaded. 
![Screenshot 2022-12-13 at 6 04 56 PM](https://user-images.githubusercontent.com/64180958/207320703-ac375dcc-bcc8-4245-9be3-791d51c8ba28.png)

## Expected behavior
When the product stock is updated, the location field should be rightly selected, and further, let upload the product. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by dt2patel** [comment]
closing ticket, handled here: https://github.com/hotwax/inventory-count/issues/127
