### ISSUE TITLE
Number of locations are appearing incorrectly and scrolling is not working in the list 

### ISSUE THREAD

**Issue by Pragyad07** [hotwax/inventory-count#129]
## Current behavior

On the count page of the product, a wrong number of locations are appearing. Therefore facility has one location, but in the inventory count app, it shows more than 1 location with the same name.

Also, scrolling is not working in the list of locations.

![Screenshot 2022-12-19 at 4 26 46 PM](https://user-images.githubusercontent.com/64180958/208413196-bb036bab-0082-4b11-8142-bbaf74ed8395.png)
![Screenshot 2022-12-19 at 4 37 53 PM](https://user-images.githubusercontent.com/64180958/208413255-68c89c0c-8bd6-49a5-9a9a-283fb0e590f4.png)

## Expected behavior

If the facility has one location, it should show only one location.
It should show exactly the same number of locations that the facility has in the oms.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by dt2patel** [comment]
closing ticket, handled here: https://github.com/hotwax/inventory-count/issues/127
