### ISSUE TITLE
Create desktop version

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/inventory-count#148]
## What is the motivation for adding/enhancing this feature?
Inventory cycle count will be done by store associates at the end of the fiscal year 2022-23. Users may use this app on a desktop but the current UI is designed for smartphone users.

## What are the acceptance criteria?
Application must be modified for desktop use.

## Can you complete this feature request by yourself?
- [ ] YES
- NO

## Additional information

Search View/Empty state: 
![Empty state](https://user-images.githubusercontent.com/119936391/214570085-b2425e0d-85a2-46b1-852c-7faa13446e8a.png)

Search View/Find product: 
![Find product](https://user-images.githubusercontent.com/119936391/214570090-4a83234d-2b03-4500-b912-eec37c70792a.png)

Upload/Wide layout:
 ![Wide layout](https://user-images.githubusercontent.com/119936391/214570141-e74bebcf-e223-48df-9ff4-70bae984fd23.png)

**Comment by Dhiraj1405** [comment]
Please find the [UI](https://www.figma.com/file/wK5FMs4z2zXQR9VfHV9ycE/Dhiraj's-Ionic-6-Material-UI-Kit-(Community)?type=design&node-id=14357%3A32791&mode=design&t=inhhCCepvgyMdF2F-1)

**Comment by ymaheshwari1** [comment]
@Dhiraj1405 I think this is no more relevant and can be closed, as we have changed the flow for inventory count app.

**Comment by Dhiraj1405** [comment]
Closing this as the inventory cycle count app is now fully revamped.
