### ISSUE TITLE
Error in selecting variance reason dropdown from count page

### ISSUE THREAD

**Issue by Pragyad07** [hotwax/inventory-count#192]
## Current behavior
Error on selecting variance reason dropdown from count page in google browser.
[Screenshot 2023-08-01 at 3 57 48 PM](https://github.com/hotwax/inventory-count/assets/64180958/4318ca29-ca03-44cb-bd64-0551c65fc0b6)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by k2maan** [comment]
@Pragyad07 the issue has been resolved, please verify.

**Comment by Pragyad07** [comment]
Verified, it is working as expected.
