### ISSUE TITLE
Add product store support in the Cycle Count app

### ISSUE THREAD

**Issue by appurvajain** [hotwax/inventory-count#193]
## What is the motivation for adding/enhancing this feature?
We need product store data selector in the Cycle Count app so that it can be used to send the cycle counts variance into Netsuite along with the product store.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Dhiraj1405** [comment]
Closing this out as there is no strong use case.
