### ISSUE TITLE
Prevent Updating Negative Inventory Counts

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/inventory-count#207]
## Current behavior
Currently, our system allows users to input negative inventory counts when uploading product inventory at stores. This poses a significant problem as it can lead to inaccuracies in inventory management and affect order fulfillment. To maintain data integrity and prevent errors, we need to implement a validation mechanism that disallows users from entering negative inventory counts.

## Expected behavior
Implement a validation rule in inventory upload to restrict users from inputting negative inventory counts. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by K-Daksh** [comment]
I would like to work on this issue. Can you assign this to me?

**Comment by ymaheshwari1** [comment]
Sure @K-Daksh

**Comment by ymaheshwari1** [comment]
Closing as not relevant, as the UI for the app has been revamped.
