### ISSUE TITLE
Enable Click Anywhere on Card to Open Detail Page on Upload Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/inventory-count#209]
## Current behavior
Currently, on the Upload page, users are required to click on specific texts within a card to navigate to the detail page. This interaction pattern might be cumbersome for users, especially on smaller devices or touchscreens. 

## Expected behavior
Implement a modification in the Upload page component to allow users to click anywhere on a card to navigate to the corresponding detail page.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Nikitaparmar04** [comment]
can you assign me this issue ?

**Comment by Dhiraj1405** [comment]
> can you assign me this issue ?

Sure, go ahead

**Comment by divyanshmangal** [comment]
can you assign me this issue?

**Comment by Lavesh12** [comment]
can you assign me this issue?

**Comment by k2maan** [comment]
@Lavesh12 @divyanshmangal please find another issue

**Comment by HarshalMahajan0110** [comment]
can you assign me this issue?

**Comment by Dhiraj1405** [comment]
> can you assign me this issue?

Please find another issue.

**Comment by Deven-ai12** [comment]
can you assign me this issue

**Comment by k2maan** [comment]
@Deven-ai12 please find another issue

**Comment by priyanshee1604** [comment]
can you assign me this issue

**Comment by ymaheshwari1** [comment]
Will be fixed by #225
