### ISSUE TITLE
Implement Spinner in Timezone Model for Timezone Configuration

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/inventory-count#210]
## Current behavior
In the timezone configuration section, it's crucial to provide visual feedback to users while the application fetches and processes timezone data. Currently, there is a lack of visual cues, leading to potential user confusion. To enhance the user experience, we propose implementing a spinner in the timezone model. This spinner will indicate loading activity, ensuring users are aware of the system processing their request.

## Expected behavior
The spinner is visible within the timezone model when the application is fetching timezone data and disappears once the timezone data has been successfully loaded and displayed in the timezone configuration section.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Nidbhagwat** [comment]
Here is the Figma link for the UI:

https://www.figma.com/file/j3l0F2DioUHEuQT53NOQJY/Ionic-6-Material-UI-Kit-(Community)-(Nidhi--2023)?type=design&node-id=25926%3A46555&mode=design&t=xRUxJOC64740RaOJ-1

**Comment by ashutosh7i** [comment]
Hello, 
I am intrested in contributing to this issue,
can you please assign it to me?

**Comment by k2maan** [comment]
Sure, @ashutosh7i go ahead
