### ISSUE TITLE
Add Toast Notification on Item Removal from Upload Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/inventory-count#213]
## Current behavior
When a user removes an item from the Upload page, it is essential to provide feedback to confirm the successful removal. Adding a toast notification will enhance the user experience by providing instant visual feedback, ensuring users are aware of the action's outcome.

## Expected behavior
Upon successful removal of an item from the Upload page, a toast notification should appear, confirming the deletion. The toast message should be concise, informing the user that the item has been removed successfully.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
Toast message: `Item removed successfully`

**Comment by mukundsolanki** [comment]
Can you assign me this issue?

**Comment by k2maan** [comment]
Sure @mukundsolanki go ahead
