### ISSUE TITLE
Integrate DXP Component: App Version Info on the Settings Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/inventory-count#214]
## What is the motivation for adding/enhancing this feature?
Integrate of the DXP component "App Version Info" into the Settings page of the application. This addition will provide users with essential information about the version of the application they are currently using. 

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by MUKHTAR-02** [comment]
can you assign this to me ?

**Comment by k2maan** [comment]
Sure @MUKHTAR-02 go ahead

**Comment by Adameddy26** [comment]
Issue verified and working fine in v1.17.0. 
https://jam.dev/c/28104f49-3eb9-471e-a842-a0ddba5f2330
