### ISSUE TITLE
Enhance Permission Management and Access Restrictions for Inventory Cycle Count App

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/inventory-count#232]
## What is the motivation for adding/enhancing this feature?
To improve the security and functionality of the Inventory Cycle Count app, we propose the following enhancements for different user roles:

a. Permission Management for Super Users, Admin Users, and Store Managers:

- Super Users will have unrestricted access to all facilities, features and configurations.
- Admin Users will have complete permissions similar to Super Users.
- Store Manager's access to the facility is restricted to facility they are associated with.
- Store Managers will have all permissions except the ability to change Quantity on Hand (QOH) view configurations.

**Additional requirement:** Display a note on the QOH configuration card, indicating that facility needs to be associated with a product store to change these configurations.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ymaheshwari1** [comment]
As per the discussion we will remove the check for product store association on login and let user login into the app when associated with facility and will not check for product store association.
