### ISSUE TITLE
Allow user to search product keyword

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#241]
## What is the motivation for adding/enhancing this feature?

I think right now we are using find product API, instead we should use product SOLR search so that we can let users search more freely

**Comment by ymaheshwari1** [comment]
@dt2patel Sir, The current api `searchProducts` also supports keyword search on `upc productId sku groupId productName productCategoryNames` parameters, so should we enable keyword search in this api itself, or should change the api to solr?

**Comment by ymaheshwari1** [comment]
As per the discussion, we will enable keyword search on the searchProducts api.
