### ISSUE TITLE
Update variance on input

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/inventory-count#245]
## Current behavior

When on the count segment of the details page, and then entering a stock quantity, the variance value does not update untill the stock input does not losses focus, this becomes quite confusing for the user as after entering the stock user does not click anywhere and directly saves the stock and might consider that the variance displayed is correct.

## Expected behavior

The value for the variance should be updated on input event of stock

## Steps to reproduce the issue

- Go to details page of any item
- Enter stock and verify that the variance field is not updated untill the stock input has focus

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

Screenshot:

![image](https://github.com/hotwax/inventory-count/assets/41404838/29e09781-73ee-49a8-8fe6-cffa5f8cc77c)

**Comment by Adameddy26** [comment]
Issue verified and working fine in 1.16.0. 
https://jam.dev/c/d9977ca9-1fa1-4a7a-b795-f4268bc6b5cb
