### ISSUE TITLE
Footer is not responsive 

### ISSUE THREAD

**Issue by PrithviKushwah** [hotwax/inventory-count#263]
## What is the motivation for adding/enhancing this feature?

![Uploading Screenshot_2024-02-18-12-51-07-354_com.android.chrome.jpg…]()

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ymaheshwari1** [comment]
@PrithviKushwah Can you check once on the screenshot link as its not working for me? Also, it would be great if you will add steps to reproduce.
