### ISSUE TITLE
Include the user name in the inventory variance comments to have more traceability. 

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/inventory-count#265]
**Description**
To make it convenient to track inventory changes on the UI, add the username to the comment. This way, we'll have a clearer picture of who's responsible for each inventory log entry from the Cycle count app making our record-keeping more straightforward and user-friendly.

**Comment by Adameddy26** [comment]
Checked in 1.16.0 and found that changes related to this enhancement are working as expected.
https://jam.dev/c/9895eb8e-46d9-444c-a880-385488f66092
