### ISSUE TITLE
Missing Empty State on Upload Page

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/inventory-count#280]
## Expected behavior
The upload page should include an empty state design that provides clear feedback to users when there are no files or content available for upload.

## Steps to reproduce the issue
Navigate to the upload page.
Observe the page when there are no files or content ready for upload.
Note that there is no visual indication or message provided to inform users about the absence of content.

## Environment details
App version : v1.17.0
App environment : UAT

## Additional information
https://jam.dev/c/258e3d1d-6407-4afd-bb11-cc7f22c4a28f

**Comment by ymaheshwari1** [comment]
Closing as not relevant, as the UI for the app has been revamped.
