### ISSUE TITLE
Adjust Cycle Count App Logic for Damaged Item Quantities

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/inventory-count#281]
## What is the motivation for adding/enhancing this feature?
Currently, the logic in the cycle count app adds quantities to inventory when store associates input the quantity of damaged items during the variance process. However, this behavior is counterintuitive and may lead to incorrect inventory adjustments. To improve usability and accuracy, we need to adjust the logic so that when associates input the quantity of damaged items, it deducts the specified quantity from inventory rather than adding it.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Dhiraj1405** [comment]
Client quote: 

```
As a store associate, if I scan an item through the cycle count app> toggle to “variance” > variance reason = damaged> if i input the qty of “1”, in the backend it should remove 1 from my inventory, not add one. 

It is more intuitive for the associates to put the damaged qty/they will assume the qty they input will be damaged out, and likely will not remember to indicate -1 when using the app to damage out. 
```

**Comment by ymaheshwari1** [comment]
Closing as the app has been revamped and the whole process has been changes, and we will be updating the app soon.
