### ISSUE TITLE
Getting error "Something went wrong" during inventory update when facility location is not created

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/inventory-count#282]
## Expected behavior
Error toast message should be generated to notify the user in case when no location is set for the facility and user is trying to update the product inventory for that facility.

## Steps to reproduce the issue
Open the Cycle Count app.
Navigate to Settings.
Select a facility that does not have its location created.
Go to the Variance/Cycle Count tab.
Add a quantity.
Select a reason for the quantity added.
Click Save.
Attempt to upload the inventory.

## Environment details
App version : V1.17.0
App environment : UAT

## Additional information
https://jam.dev/c/a1c1e61a-524f-4c5d-9643-3c51575dc887

**Comment by ymaheshwari1** [comment]
Closing as not relevant, as app's UI and its functionality has been revamped.
