### ISSUE TITLE
Scan button overlaps the last product on the search page

### ISSUE THREAD

**Issue by NamanTech** [hotwax/inventory-count#3]
Screenshots:

![localhost_8100_search](https://user-images.githubusercontent.com/84688675/137116039-56996b45-6aea-4b61-b0cc-c0599445fa1f.png)

Steps to reproduce:

Login into the application.
Search for a product. (for example, use MH to search products)
Scroll till the bottom of the page.

**Comment by k2maan** [comment]
Seems to be fixed. Closing.
