### ISSUE TITLE
Implement support to download csv for closed cycle counts

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/inventory-count#341]
## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by Adameddy26** [comment]
@ymaheshwari1 It is found that there is no effect of filters on the downloaded CSV report. Hence, reopening this ticket.

**Comment by Adameddy26** [comment]
Issue verified and working fine in DEV environment of App version inventory-count-2.0-9c89de2.
Hence, closing this issue.
