### ISSUE TITLE
Select product identifier position in settings

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#345]
## Current behavior

The product identifier selector for the cycle count app should show in the app section not the OMS section. Please refer to all apps with the same card for reference.

**Comment by ymaheshwari1** [comment]
Will be fixed in https://github.com/hotwax/inventory-count/pull/366

**Comment by Adameddy26** [comment]
Issue verified and working fine. Hence, closing this ticket.
![image](https://github.com/user-attachments/assets/a2a8eae5-306d-46ac-9152-e366385cbe3b)
