### ISSUE TITLE
Disable Assign Button until facility selected

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#346]
## Current behavior

The assign count button should be disabled until a facility has been assigned to the count. On hover we can show a toast that a facility must be added.

**Comment by ymaheshwari1** [comment]
@dt2patel Sir, we can disable the button if facility is not assigned but once a button is disabled pointer events won't work, thus won't be able to show toast on hover.

If we want to achieve this we need to remove the pointer-events property from the disabled class.

**Comment by dt2patel** [comment]
After discussion, and this comment from @ymaheshwari1 we can close this ticket
