### ISSUE TITLE
Product not added to list after search box is cleared.

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#348]
## Current behavior

https://jam.dev/c/c56e2e51-94ad-4b2a-ad20-5652e23b7d19

**Comment by ymaheshwari1** [comment]
I think here we can simply remove the searched product once the user clears the input field, as we also allow user to add product to count on `enter` key press and then in that case if input does not have any value but searched product will, then it will lead to confusion.

**Comment by dt2patel** [comment]
correct, after clearing search box, search result should also be cleared.

**Comment by ymaheshwari1** [comment]
Fixed in https://github.com/hotwax/inventory-count/pull/390

**Comment by Adameddy26** [comment]
Issue verified and working fine in DEV environment of App version - INVENTORY-COUNT-2.0-580A565.
https://jam.dev/c/4335aa34-d999-4325-b55a-14cf9a354521

Hence, closing this issue.
