### ISSUE TITLE
Rejection history not showing

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#350]
## Current behavior

Item is not showing rejection history when adding items to count:

<img width="1114" alt="Screenshot 2024-07-12 at 3 01 26 PM" src="https://github.com/user-attachments/assets/447fb39b-5a36-4c30-bb41-a23a2e5c8e74">
https://dev-oms.hotwax.io/commerce/control/ViewOrder?orderId=10390

<img width="1364" alt="Screenshot 2024-07-12 at 3 01 42 PM" src="https://github.com/user-attachments/assets/80c4727e-cc9b-4c61-bc99-5903ea689a8f">

Count ID:
100663

**Comment by ymaheshwari1** [comment]
We will pick this once the api will have support for returning rejection history of items.

**Comment by dt2patel** [comment]
Until then we should hide this from UI then

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.0.0. Hence, closing it.
