### ISSUE TITLE
Clicking on date chip does not allow date change

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#351]
## Current behavior

Clicking on the date chip should allow the user to change the due date of the cycle count

<img width="574" alt="Screenshot 2024-07-12 at 3 05 25 PM" src="https://github.com/user-attachments/assets/e6e2db84-8156-4f2a-8a82-761ea329667b">

**Comment by Adameddy26** [comment]
Issue verified and working fine. Hence, closing it.
https://jam.dev/c/db37d1a6-f131-4b12-a56c-84b7d756f4c8
