### ISSUE TITLE
Sticky scrolling on counting page

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#353]
## What is the motivation for adding/enhancing this feature?

In the counter view, when the user opens a count detail page and scrolls the product list in the left column, the whole page scrolls. Instead only the product list should scroll. Its search and segments section should remain sticky. The rest of the page should not move at all.

<img width="1267" alt="Screenshot 2024-07-12 at 3 14 37 PM" src="https://github.com/user-attachments/assets/3a598d20-a714-4ee5-9134-531101e04ab3">

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.0.0. Hence, closing this ticket.
https://jam.dev/c/de141905-c5ef-4098-9f68-88d24904f9ce
