### ISSUE TITLE
Count details not reflected accurately when saving count

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#354]
## Current behavior

When counting individual items from the counter view, the count details for who counted and when are not populating:

<img width="932" alt="Screenshot 2024-07-12 at 3 16 45 PM" src="https://github.com/user-attachments/assets/a817aa31-9353-4cc9-ad8e-a067ab796c4c">

https://jam.dev/c/ac408c7f-8a0a-45df-a099-5f4104d2bd38

**Comment by ymaheshwari1** [comment]
For now removed the `counted at`, as we do not have the time when the item was counted, will add it again once the information is available.

**Comment by Adameddy26** [comment]
Issue verified and working fine. Hence, closing it.
![image](https://github.com/user-attachments/assets/174d3dee-f1f2-4643-986c-ce6ce4a6492a)
