### ISSUE TITLE
highlight currently selected item during counting

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#355]
## What is the motivation for adding/enhancing this feature?

show selected item during count page

<img width="1319" alt="Screenshot 2024-07-12 at 3 18 47 PM" src="https://github.com/user-attachments/assets/80d45811-38a2-43b1-bd08-d371fb1a4d8c">

**Comment by Adameddy26** [comment]
Verified the changes and are working fine. Hence, closing this ticket.
![image](https://github.com/user-attachments/assets/b395e160-3bda-4d2f-b664-8430315e7582)
