### ISSUE TITLE
Counting detail page UI Revamp

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#357]
## What is the motivation for adding/enhancing this feature?

Few points for the count detail page:

Change primary product id to H1 tag
Change save count button to primary filled button not outline
Add next and back buttons on the count detail screen (fixed to do not scroll with products)
Add scroll snapping so that if user scrolls down on the detail section, they land on the next product

<img width="855" alt="Screenshot 2024-07-12 at 3 34 45 PM" src="https://github.com/user-attachments/assets/20e8603b-329a-4d8b-8f17-03bd602cc8a4">

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.0.0. Hence, closing it.
https://jam.dev/c/de141905-c5ef-4098-9f68-88d24904f9ce
