### ISSUE TITLE
Search products not working in count detail page

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#360]
## Current behavior

<img width="1458" alt="Screenshot 2024-07-12 at 3 53 15 PM" src="https://github.com/user-attachments/assets/dcc3dc99-80aa-4646-892c-e1e87ff03e68">
Item search not working in product count list

https://jam.dev/c/47d5b634-03cb-43ca-a53d-5d5e03c959a7

**Comment by Adameddy26** [comment]
Issue verified and working fine. Hence, closing it.
https://jam.dev/c/34785087-2f5e-4f4f-b2c2-71ea7d9b28c8
