### ISSUE TITLE
Select all selecting items other than those in view

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#361]
## Current behavior

Select all should only select items which are in the current segment. It will be used by user to select all items they have filtered out and approve them at once:

https://jam.dev/c/b6932f34-d66f-40a2-ae40-ab33baf7a4b1

Reselecting the select all button should un select all selected items. If there is a partial selection then it should select all out standing items.

**Comment by Adameddy26** [comment]
@ymaheshwari1 There is no tick appearing on clicking the select all button on pending review screen.
Please have a look.

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 There is no tick appearing on clicking the select all button on pending review screen. Please have a look.

Already fixed, please check.

**Comment by Adameddy26** [comment]
> > @ymaheshwari1 There is no tick appearing on clicking the select all button on pending review screen. Please have a look.
> 
> Already fixed, please check.

I think there is some miscommunication. I was saying that there is no tick appearing inside the square box present in the top right(to select all) on clicking that button. This is occurring if rejected item is present on the pending review screen. This is an issue and needs to be fixed.

**Comment by Adameddy26** [comment]
Verified the issue and it is working fine. Hence, closing this ticket.
https://jam.dev/c/541be7d5-5d6f-4571-9ddd-8090c0f50c5c
