### ISSUE TITLE
Items variance percentage calculation incorrect

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#362]
## Current behavior

Seems like positive variance % calculation is not happening correctly. Even with 1 of 9 variance, it is showing in 20%+ variance range.

https://jam.dev/c/4abcc81c-3bce-4d90-abc2-13e881239359

**Comment by Adameddy26** [comment]
Issue verified and working fine. Hence, closing it.
https://jam.dev/c/19afefa4-e911-4e9f-8b51-454d42c16cfe
