### ISSUE TITLE
Item persists in Pending Review after reassignment and removal in Inventory Count

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/inventory-count#376]
## Current behavior
The item appears in the Pending Review section even though it was removed from the Assigned section.

## Expected behavior
The item should not appear in the Pending Review section after being removed from the Assigned section and saved.

## Steps to reproduce the issue
Add one item to the Pending Review section.
Confirm that the item appears as "not counted" after addition.
Do not accept or reject the item; instead, re-assign the whole inventory count.
Observe that the inventory count moves to the Assigned section.
Open the inventory count from the Assigned section.
Remove the item that was initially added to the Pending Review screen.
Save the changes to move the inventory count back to the Pending Review section.
Open the Pending Review screen and observe that the item removed from the Assigned section still appears in the Pending Review screen.

## Environment details
App version : INVENTORY-COUNT-2.0-E02AD11
App environment : DEV

**Comment by ymaheshwari1** [comment]
Linked PR: https://github.com/hotwax/inventory-count/pull/374

**Comment by Adameddy26** [comment]
Issue verified and working fine in DEV environment of App version INVENTORY-COUNT-2.0-BEE32C4
Hence, closing this ticket.
