### ISSUE TITLE
Product identifier setting not persisting

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#417]
## Current behavior

The product identifier setting is not persisting on the dev version of the app.

Steps:
https://jam.dev/c/704fac61-0a4c-4404-b6c4-bccf512dcd23
Log into dev environment
app will default to internal id
Go to settings -> select internal name

logout of app, log back in
App will revert to internal id

**Comment by ymaheshwari1** [comment]
It was due to multiple existence of the product identifier setting, due to which the values are getting over-ridden, I have deleted the duplicate record for this setting.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.0.0. Hence, closing it.
https://jam.dev/c/1dabe982-36fd-429b-9b93-8bac7c856412
