### ISSUE TITLE
Update threshold slider in real time

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#419]
## What is the motivation for adding/enhancing this feature?

When using the variance threshold slider, the percentage number should update in realtime

<img width="449" alt="Screenshot 2024-08-06 at 5 50 20 PM" src="https://github.com/user-attachments/assets/f79d6777-e5c9-4754-ab41-e35e32d6de1a">

**Comment by Adameddy26** [comment]
Verified and working fine in DEV envIronment of App version inventory-count-2.0-dc37447.
Hence, closing this ticket.
