### ISSUE TITLE
Filters not working on completed page

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#420]
## Current behavior

Filter button currently does not show the selected facilities like the Figma designs and also doesn't have support for date range filters:

<img width="973" alt="Screenshot 2024-08-06 at 7 36 14 PM" src="https://github.com/user-attachments/assets/c0020fdf-ad12-4fbc-9875-0f0ddd4e73af">

**Comment by Adameddy26** [comment]
Verified the changes in DEV environment of App version inventory-count-2.0-dc37447 and found that selected facilities names are visible in the filter pane.
Also the date field is not yet implemented inside the filters due to lack of API support. 
Hence, moving this item to backlog.

**Comment by dt2patel** [comment]
Instead of showing all facilities in one item, use one item per facility.

**Comment by ymaheshwari1** [comment]
Updated UI:

![image](https://github.com/user-attachments/assets/206cc882-1134-46aa-bbe3-429ee2599ed2)

**Comment by dt2patel** [comment]
looks good to me

**Comment by AnanyaSikarwar** [comment]
I want to contribute

**Comment by ymaheshwari1** [comment]
@AnanyaSikarwar Go ahead

**Comment by ymaheshwari1** [comment]
@Adameddy26 Let me know if this can be closed, as this is already resolved and for date range filter we can create a separate issue and link that with this one.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.2.0. Hence, closing this issue.
