### ISSUE TITLE
Remove edit option from rejected and accepted items

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#421]
## Current behavior

Rejected and accepted items can no longer be edited, so the option to recount should not be visible:
<img width="987" alt="Screenshot 2024-08-06 at 7 45 27 PM" src="https://github.com/user-attachments/assets/b6eca095-fbe2-4991-9d32-d4c3bd51c2ee">

**Comment by ymaheshwari1** [comment]
This will be fixed in https://github.com/hotwax/inventory-count/pull/416.

Also we have added check to not display variance when the item is rejected, as there is no relevant case where user wants to see the variance in the above case.
