### ISSUE TITLE
Display facility name in place of static text `Count Name` on store view list screen

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/inventory-count#440]
## What is the motivation for adding/enhancing this feature?

We are displaying static text `Count Name` on the list page of store view screens that is not helpful for the user, instead we should display the currently selected facility so that user get to know for which facility they are checking the counts.

We are only thinking about changing this for the list page and not for the details page of the count, as displaying the currently selected count name on the details page is helpful.

- Go to count page by changing the url to `/tabs/count` and check the issue.

## What are the acceptance criteria?

- [ ] Display current selected facility name in the header

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Additional information

![image](https://github.com/user-attachments/assets/d64c0c3b-0c5f-4a52-a17c-b484aa982a0f)

**Comment by mustang006** [comment]
i would like to handle this

**Comment by ymaheshwari1** [comment]
Sure @mustang006

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.3.0. Hence, closing this issue.
![image](https://github.com/user-attachments/assets/e963e82f-be64-4892-99de-c0b4ed2cc104)
