### ISSUE TITLE
Item change buttons are not displayed correctly after changing tabs

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/inventory-count#442]
## Current behavior

When we are on the details page of a count and then if we switch the tabs then the both buttons to change the items becomes active, but on mouse scroll then buttons changes the state and then displayed correctly.

## Expected behavior

The buttons should always displayed correctly even when switching the tabs

## Steps to reproduce the issue

- Go to count detail page on store view screen
- Change the tab and verify that the button to move up becomes active
- Scroll on the image and see that the button to move up is active even when there is no item above the current item.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.3.0. Hence, closing this issue.
Before(Prod) - https://jam.dev/c/799e414b-9c2b-4c66-b838-264a5ead4fc7
After(UAT) - https://jam.dev/c/9831a4a0-c027-4439-be2f-01b74fcccb51
