### ISSUE TITLE
When on draft bulk page no menu item is enabled

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/inventory-count#445]
## Current behavior

When on the draft bulk page no menu item is displayed as selected

## Expected behavior

The draft menu item should be displayed as selected when on draft bulk page

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

![image](https://github.com/user-attachments/assets/505b9077-357c-45fb-b8ef-5e5e0f06f5ed)

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.3.0. Hence, closing this issue.
![image](https://github.com/user-attachments/assets/dd63a8af-c597-416e-a026-a0842d458f86)
