### ISSUE TITLE
Extra .csv Suffix Appearing in Recently Uploaded Files on Draft Bulk Page

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/inventory-count#450]
## Current behavior
The file name appears as example_file.csv.csv.

## Expected behavior
The file name should appear as example_file.csv without any additional suffix.

## Steps to reproduce the issue
Navigate to the draft bulk page.
Upload a CSV file (e.g., example_file.csv).
Observe the file name displayed in the recently uploaded files section.

## Environment details
App version: v2.1.0
App environment: UAT

## Additional information
https://jam.dev/c/6a69dea0-fe70-4a74-a25e-59f9e01ce5ee

**Comment by ravilodhi** [comment]
@Adameddy26 Could you please check this issue one more time. I think this issue has already been fixed.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.1.3. Hence, closing this issue.
![image](https://github.com/user-attachments/assets/3a023847-2c8c-43e8-b1ca-9b8821327b68)
