### ISSUE TITLE
Only Current Year (2024) Visible for Due Date Selection in Draft, Assigned, or Pending Review Tab

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/inventory-count#470]
## Current behavior
Only dates within the current year (2024) are available for selection.

## Expected behavior
Users should be able to select due dates from other years (future).

## Steps to reproduce the issue
Login the app using admin account.
Navigate to the Draft, Assigned, or Pending Review tab.
Attempt to set or modify the due date for any count.
Observe that only the current year 2024 is visible for selection.

## Environment details
App version : v2.1.2
App environment : Uat

## Additional information
![image](https://github.com/user-attachments/assets/00adb728-0165-411e-bf2b-eaa51192101d)

**Comment by ishitmodi** [comment]
I want to contribute

**Comment by ymaheshwari1** [comment]
Sure @ishitmodi

**Comment by ishitmodi** [comment]
Changed The Branch Name To #470

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.3.0. Hence, closing this issue.
![image](https://github.com/user-attachments/assets/1998cba1-5f24-4239-bf29-e591aecf96da)
