### ISSUE TITLE
Custom theme file

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#5]
Add a custom theme file like in [Clienteling app](https://github.com/hotwax/clienteling/tree/main/src/theme).

Add custom fonts, Montserrat for headings and open sans for body.

This will allow any brand to customize the look and feel of any app.

**Comment by amit9177yadav** [comment]
I Ready to contribute

**Comment by amit9177yadav** [comment]
I am ready to contribute

**Comment by adityasharma7** [comment]
@dt2patel 
Should we close this?
