### ISSUE TITLE
Change the scroll up/down button and center align empty state message

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/inventory-count#500]
## What is the motivation for adding/enhancing this feature?

- Center align the empty state message for no product found.
- Change the buttons to scrolling count items up/down as shown in below picture.
![Screenshot from 2024-11-11 17-58-58](https://github.com/user-attachments/assets/9ad5ed95-cc8f-40d5-8964-ab29ab407540)

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.3.0. Hence, closing this issue.
https://jam.dev/c/44986558-7006-4043-9d2d-4dd83d970bc4
