### ISSUE TITLE
Show errored uploads

### ISSUE THREAD

**Issue by dt2patel** [hotwax/inventory-count#525]
## What is the motivation for adding/enhancing this feature?

When a draft count is uploaded, the user doesn't have any visibility into what they did wrong. We should show error uploads for 24 hours after they happen.

<img width="1023" alt="Screenshot 2024-11-25 at 7 49 23 PM" src="https://github.com/user-attachments/assets/d108cf91-669c-46ad-bc0c-588ec5f5be06">

Clicking on view error should open a modal that shows the error in details and a link to the upload user guide:
<img width="718" alt="Screenshot 2024-11-25 at 7 50 02 PM" src="https://github.com/user-attachments/assets/72238eef-88a1-4dc6-b5c0-e71cca92104f">

Link to user manual:
https://docs.hotwax.co/documents/retail-operations/inventory/introduction/draft-cycle-count

Also as part of this we should add details of expected date format:
<img width="249" alt="Screenshot 2024-11-25 at 7 50 41 PM" src="https://github.com/user-attachments/assets/b219a22c-7ef8-4d32-8728-23384d79ff33">

**Comment by ravilodhi** [comment]
Depends on Maarg changes.

**Comment by priyanshee1604** [comment]
The following issue has been verified on the Cycle Count App (Dev instance):

1. After uploading the correct file, the user is able to view it successfully.
2. The due date format is specified as expected.
3. An error modal is displayed if there is an error during file processing with appropriate reason.
